In [1]:
import numpy as np

In [2]:
# Step 1: Define token embeddings (7 tokens, d_model = 8)
np.random.seed(42)
tokens = ["What", "are", "the", "symptoms", "of", "diabetes", "?"]
d_model = 8   # embedding dimension
seq_len = len(tokens)

In [3]:
# Simulate input embeddings (in practice these come from nn.Embedding)
X = np.random.randn(seq_len, d_model)   # shape: (7, 8)

In [4]:
# Step 2: Define weight matrices for Q, K, V
d_k = 8   # key/query dimension
W_Q = np.random.randn(d_model, d_k)    # (8, 8)
W_K = np.random.randn(d_model, d_k)    # (8, 8)
W_V = np.random.randn(d_model, d_k)    # (8, 8)

In [5]:
# Step 3: Compute Q, K, V projections
Q = X @ W_Q    # (7, 8)
K = X @ W_K    # (7, 8)
V = X @ W_V    # (7, 8)

In [6]:
# Step 4: Compute scaled dot-product attention scores
#   Attention(Q, K, V) = softmax(Q * K^T / sqrt(d_k)) * V
scores = Q @ K.T / np.sqrt(d_k)   # (7, 7)

In [7]:
# Step 5: Apply Softmax row-wise to get attention weights
def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))  # numerical stability
    return e_x / e_x.sum(axis=-1, keepdims=True)

attention_weights = softmax(scores)   # (7, 7)

In [8]:
# Step 6: Compute the final attended output
output = attention_weights @ V        # (7, 8)

# ─── Print Results ───
print("Tokens:", tokens)
print()
print("Attention Weights (each row = how token attends to others):")
print(np.round(attention_weights, 3))
print()
print("Self-Attention Output (new token representations):")
print(np.round(output, 3))


Tokens: ['What', 'are', 'the', 'symptoms', 'of', 'diabetes', '?']

Attention Weights (each row = how token attends to others):
[[0.    0.001 0.    0.205 0.466 0.006 0.321]
 [0.773 0.    0.224 0.001 0.    0.    0.002]
 [0.133 0.019 0.013 0.    0.809 0.023 0.004]
 [0.029 0.    0.207 0.125 0.    0.    0.639]
 [0.753 0.069 0.021 0.157 0.    0.001 0.   ]
 [0.189 0.    0.049 0.736 0.    0.    0.026]
 [0.001 0.015 0.    0.    0.981 0.001 0.001]]

Self-Attention Output (new token representations):
[[-5.200e-01 -1.565e+00 -6.890e-01  3.950e-01 -1.310e-01 -1.188e+00
   5.690e-01  2.150e-01]
 [ 3.390e-01  2.520e+00  3.587e+00  2.548e+00 -2.023e+00 -2.520e-01
  -8.730e-01  1.574e+00]
 [ 8.600e-02 -2.935e+00 -1.779e+00  9.610e-01  1.934e+00 -3.053e+00
   2.342e+00 -7.230e-01]
 [-8.730e-01 -6.110e-01  1.207e+00 -4.770e-01 -1.985e+00  2.450e-01
  -1.008e+00  1.363e+00]
 [ 3.720e-01  3.707e+00  3.620e+00  3.217e+00 -2.629e+00  2.310e-01
  -1.256e+00  1.846e+00]
 [-6.500e-01  8.970e-01 -1.900e-02  1.21